version: 2.1

orbs:
  ios: wordpress-mobile/ios@0.0.29

executors:
  xcode:
    

jobs:
  build-tests:
    executor:
      name: ios/default
      xcode-version: "10.2.0"
    steps:
      - checkout
      - ios/install-dependencies:
          bundle-install: true
          pod-install: true
      - ios/xcodebuild:
          command: build-for-testing
          arguments: -workspace 'WordPress.xcworkspace' -scheme 'WordPressUITests' -configuration 'Debug' -sdk iphonesimulator -derivedDataPath DerivedData
      - ios/xcodebuild:
          command: build-for-testing
          arguments: -workspace 'WordPress.xcworkspace' -scheme 'WordPress' -configuration 'Debug' -sdk iphonesimulator -derivedDataPath DerivedData
      - persist_to_workspace:
          root: ./
          paths:
            - DerivedData/Build/Products
            - Pods/WordPressMocks
  run-tests:
    parameters:
      scheme:
        type: string
      device:
        type: string
      run-mocks:
        type: boolean
    executor:
      name: ios/default
      xcode-version: "10.2.0"
    steps:
      - ios/boot-simulator:
          xcode-version: "10.2.0"
          device: << parameters.device >>
      - attach_workspace:
          at: ./
      - when:
          condition: << parameters.run-mocks >>
          steps:
            - run:
                name: Run mocks
                command: ./Pods/WordPressMocks/scripts/start.sh 8282
                background: true
      - ios/wait-for-simulator
      - ios/xcodebuild:
          command: test-without-building
          arguments: -xctestrun DerivedData/Build/Products/<< parameters.scheme >>_iphonesimulator12.2-x86_64.xctestrun -destination "platform=iOS Simulator,id=$SIMULATOR_UDID"
      - ios/save-xcodebuild-artifacts

workflows:
  wordpress_ios:
    jobs:
      - build-tests:
          name: Build Tests
      - run-tests:
          name: Unit Tests (iPhone Xs)
          device: iPhone Xs
          run-mocks: false
          scheme: WordPress
          requires: [ "Build Tests" ]
      - run-tests:
          name: UI Tests (iPhone Xs)
          device: iPhone Xs
          run-mocks: true
          scheme: WordPressUITests
          requires: [ "Build Tests" ]
      - run-tests:
          name: UI Tests (iPad 6th generation)
          device: iPad \\(6th generation\\)
          run-mocks: true
          scheme: WordPressUITests
          requires: [ "Build Tests" ]
