version: 2.1

orbs:
  ios: wordpress-mobile/ios@0.0.32
  git: wordpress-mobile/git@0.0.32

jobs:
  Build Tests:
    executor:
      name: ios/default
      xcode-version: "10.2.0"
    steps:
      - git/shallow-checkout
      - ios/install-dependencies:
          bundle-install: true
          pod-install: true
      - ios/xcodebuild:
          command: build-for-testing
          arguments: -workspace 'WordPress.xcworkspace' -scheme 'WordPressUITests' -configuration 'Debug' -sdk iphonesimulator -derivedDataPath DerivedData
      - ios/xcodebuild:
          command: build-for-testing
          arguments: -workspace 'WordPress.xcworkspace' -scheme 'WordPress' -configuration 'Debug' -sdk iphonesimulator -derivedDataPath DerivedData
      - persist_to_workspace:
          root: ./
          paths:
            - DerivedData/Build/Products
            - Pods/WordPressMocks
  Unit Tests:
    executor:
      name: ios/default
      xcode-version: "10.2.0"
    steps:
      - ios/boot-simulator:
          xcode-version: "10.2.0"
          device: iPhone XS
      - attach_workspace:
          at: ./
      - ios/wait-for-simulator
      - ios/xcodebuild:
          command: test-without-building
          arguments: -xctestrun DerivedData/Build/Products/WordPress_iphonesimulator12.2-x86_64.xctestrun -destination "platform=iOS Simulator,id=$SIMULATOR_UDID"
      - ios/save-xcodebuild-artifacts
  UI Tests:
    parameters:
      device:
        type: string
    executor:
      name: ios/default
      xcode-version: "10.2.0"
    steps:
      - ios/boot-simulator:
          xcode-version: "10.2.0"
          device: << parameters.device >>
      - attach_workspace:
          at: ./
      - run:
          name: Run mocks
          command: ./Pods/WordPressMocks/scripts/start.sh 8282
          background: true
      - ios/wait-for-simulator
      - ios/xcodebuild:
          command: test-without-building
          arguments: -xctestrun DerivedData/Build/Products/WordPressUITests_iphonesimulator12.2-x86_64.xctestrun -parallel-testing-enabled YES -parallel-testing-worker-count 2 -destination "platform=iOS Simulator,id=$SIMULATOR_UDID"
      - ios/save-xcodebuild-artifacts

workflows:
  wordpress_ios:
    jobs:
      - Build Tests
      - Unit Tests:
          requires: [ "Build Tests" ]
      - UI Tests:
          name: UI Tests (iPhone Xs)
          device: iPhone Xs
          requires: [ "Build Tests" ]
      - UI Tests:
          name: UI Tests (iPad 6th generation)
          device: iPad \\(6th generation\\)
          requires: [ "Build Tests" ]
